### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by tishihtzu** [clandmeter/alpine-docker-gitlab#20]
I am new to this image. I read the readm.md and modified your docker-compose.yaml:
``` yaml
# 241205: trying out this instance.
# jon@gatorbot.com

services:
  gitlab:
    image: alpinelinux/alpine-docker-gitlab
    build: gitlab
    hostname: ${GITLAB_HOSTNAME}
    restart: always
    volumes:
      - ${VOLUME_ROOT}/repositories:/home/git/repositories
      - ${VOLUME_ROOT}/config:/etc/gitlab
      - ${VOLUME_ROOT}/log:/var/log
      - ${VOLUME_ROOT}/builds:/home/git/gitlab/builds
      - ${VOLUME_ROOT}/shared:/home/git/gitlab/shared
      - ${VOLUME_ROOT}/uploads:/home/git/gitlab/public/uploads
      - ${VOLUME_ROOT}/plugins:/home/git/gitlab/plugins
    ports:
      - "2222:22"
      - "8064:80"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      GITLAB_BACKUP_SKIP: "true"
      GITLAB_USE_PUMA: "true"

  postgres:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ${VOLUME_ROOT}/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - ${VOLUME_ROOT}/redis:/data
    entrypoint: redis-server --appendonly yes

```
_Yes, I have a `.env` file defined with those variables._

I receved a bunch of  permissions errors (see attached):
[241206-1449.log](https://github.com/user-attachments/files/18044704/241206-1449.log)

Thoughts?

Tnx,
Jon
